name: CI

on:
  push:
    branches: [main, feat/*, fix/*]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    env:
      XDEBUG_MODE: coverage
      COMPOSER_ALLOW_SUPERUSER: 1
      COMPOSER_NO_INTERACTION: 1
      COMPOSER_MEMORY_LIMIT: -1

    strategy:
      matrix:
        php-version: ["7.4", "8.0", "8.1", "8.2", "8.3", "8.4"]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: xdebug, zip, unzip
          coverage: xdebug
          ini-values: xdebug.mode=coverage

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-version }}-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run test suite
        run: composer test

      - name: Display coverage summary
        run: cat coverage.txt

      - name: Upload coverage reports to Codecov
        if: matrix.php-version == '8.1'
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          fail_ci_if_error: false

      - name: Archive test artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-php-${{ matrix.php-version }}
          path: |
            tests/log
            tests/configs
          retention-days: 7

  dependency-scan:
    name: Dependency Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run security checker
        uses: symfonycorp/security-checker-action@v5
