name: Code Quality

on:
  push:
    branches: [main, feat/*, fix/*]
  pull_request:
    branches: [main]

jobs:
  code-style:
    name: Code Style Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: php-cs-fixer, phpcs

      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-8.1-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-8.1-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Check PHP syntax
        run: find src tests -name "*.php" -exec php -l {} \;

    # Uncomment if you add phpcs to your project
    # - name: Run PHP CodeSniffer
    #   run: phpcs src tests --standard=PSR12

    # Uncomment if you add php-cs-fixer to your project
    # - name: Run PHP CS Fixer (dry-run)
    #   run: php-cs-fixer fix --dry-run --diff --verbose

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: phpstan

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-8.1-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-8.1-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

    # Uncomment if you add phpstan to your project
    # - name: Run PHPStan
    #   run: phpstan analyse src --level=5
